In [2]:
# Import our tools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

print("All libraries loaded successfully!")

All libraries loaded successfully!


In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df = sns.load_dataset('iris')
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
df['species']=df['species'].map({'setosa':1, 'versicolor':2, 'virginica':3})
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,1
1,4.9,3.0,1.4,0.2,1
2,4.7,3.2,1.3,0.2,1
3,4.6,3.1,1.5,0.2,1
4,5.0,3.6,1.4,0.2,1
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,3
146,6.3,2.5,5.0,1.9,3
147,6.5,3.0,5.2,2.0,3
148,6.2,3.4,5.4,2.3,3


In [9]:
x = df.drop(columns=['species'])
y = df['species']

print('x shape:',x.shape)
print('y shape:',y.shape)

x shape: (150, 4)
y shape: (150,)


In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=10)

print('Training set:', x_train.shape)
print('Test set:', x_test.shape)

Training set: (105, 4)
Test set: (45, 4)


In [11]:
model = LogisticRegression(max_iter=100)
model.fit(x_train, y_train)
print('model trained successfully')

model trained successfully


C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
y_pred  = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'accuracy:{accuracy * 100:.2f}%')

cm = confusion_matrix(y_test, y_pred)
print('\n confusion matrix')
print(cm)

accuracy:100.00%

 confusion matrix
[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]


In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        17
           3       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [14]:
from sklearn.ensemble import RandomForestClassifier

model_rf =  RandomForestClassifier(n_estimators=5, random_state=20)
model_rf.fit(x_train, y_train)
print('model trained successfully')

model trained successfully


In [16]:
y_pred_rf = model_rf.predict(x_test)
accuracy_rf= accuracy_score(y_test, y_pred_rf)
print(f'Random Forest Accuracy:{accuracy_rf * 100:.2f}%')

# Full report
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy:93.33%
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       0.94      0.88      0.91        17
           3       0.87      0.93      0.90        14

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45



In [18]:
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(x_train, y_train)
y_pred_dt = model_dt.predict(x_test)

print("DECISION TREE")
print(f"Accuracy: {accuracy_score(y_test, y_pred_dt)*100:.2f}%")
print(classification_report(y_test, y_pred_dt))

DECISION TREE
Accuracy: 97.78%
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       0.94      1.00      0.97        17
           3       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [20]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=3)
model_knn.fit(x_train, y_train)
y_pred_knn = model_knn.predict(x_test)

print("KNN")
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn)*100:.2f}%")
print(classification_report(y_test, y_pred_knn))

KNN
Accuracy: 97.78%
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      0.94      0.97        17
           3       0.93      1.00      0.97        14

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [21]:
from sklearn.svm import SVC

model_svm = SVC(kernel='rbf', random_state=42)
model_svm.fit(x_train, y_train)
y_pred_svm = model_svm.predict(x_test)

print("SVM")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm)*100:.2f}%")
print(classification_report(y_test, y_pred_svm))

SVM
Accuracy: 100.00%
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        17
           3       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [22]:
from sklearn.naive_bayes import GaussianNB

model_nb = GaussianNB()
model_nb.fit(x_train, y_train)
y_pred_nb = model_nb.predict(x_test)

print("NAIVE BAYES")
print(f"Accuracy: {accuracy_score(y_test, y_pred_nb)*100:.2f}%")
print(classification_report(y_test, y_pred_nb))

NAIVE BAYES
Accuracy: 100.00%
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        17
           3       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [24]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# XGBoost needs numbers not text for target
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

model_xgb = XGBClassifier(random_state=42)
model_xgb.fit(x_train, y_train_encoded)
y_pred_xgb = model_xgb.predict(x_test)

print("XGBOOST")
print(f"Accuracy: {accuracy_score(y_test_encoded, y_pred_xgb)*100:.2f}%")

XGBOOST
Accuracy: 97.78%


In [26]:
results = {
    'Logistic Regression': accuracy_score(y_test, y_pred),
    'Decision Tree': accuracy_score(y_test, y_pred_dt),
    'Random Forest': accuracy_score(y_test, y_pred_rf),
    'KNN': accuracy_score(y_test, y_pred_knn),
    'SVM': accuracy_score(y_test, y_pred_svm),
    'Naive Bayes': accuracy_score(y_test, y_pred_nb),
    'XGBoost': accuracy_score(y_test_encoded, y_pred_xgb)
}

print("\nMODEL COMPARISON")
print("-" * 35)
for model, acc in sorted(results.items(), 
                          key=lambda x: x[1], 
                          reverse=True):
    print(f"{model:25} {acc*100:.2f}%")


MODEL COMPARISON
-----------------------------------
Logistic Regression       100.00%
SVM                       100.00%
Naive Bayes               100.00%
Decision Tree             97.78%
KNN                       97.78%
XGBoost                   97.78%
Random Forest             93.33%
